const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Eurika/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright');
const source=path.resolve(process.argv[2]),output=path.resolve(process.argv[3]);
const pdfjs=process.env.PDFJS_ROOT||'C:/Users/Eurika/AppData/Local/npm-cache/_npx/7673eca99d5dbcb2/node_modules/pdfjs-dist';
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');if(url.pathname==='/')return res.writeHead(200,{'Content-Type':'text/html'}).end('<html><body style="margin:0;background:white"><canvas id="page"></canvas></body></html>');if(url.pathname==='/document.pdf')return res.writeHead(200,{'Content-Type':'application/pdf'}).end(fs.readFileSync(source));const file=path.resolve(pdfjs,'.'+url.pathname.replace('/pdfjs',''));if(!file.startsWith(path.resolve(pdfjs)+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,data)=>{if(error)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':file.endsWith('.mjs')?'text/javascript':'application/octet-stream'}).end(data);});});
(async()=>{let browser;await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{
browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);
const metadata=await page.evaluate(async()=>{const pdfjs=await import('/pdfjs/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdfjs/build/pdf.worker.mjs';window.pdf=await pdfjs.getDocument({url:'/document.pdf',standardFontDataUrl:'/pdfjs/standard_fonts/'}).promise;return {pages:window.pdf.numPages};});
fs.mkdirSync(path.dirname(output),{recursive:true});const pages=[];
for(let number=1;number<=metadata.pages;number++){const detail=await page.evaluate(async number=>{const p=await window.pdf.getPage(number),view=p.getViewport({scale:3}),canvas=document.getElementById('page');canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);await p.render({canvasContext:canvas.getContext('2d'),viewport:view}).promise;const items=(await p.getTextContent()).items;return {page:number,dimensions:p.view,text:items.map(i=>i.str).join(' '),items:items.filter(i=>i.str.trim()).map(i=>({text:i.str,x:i.transform[4],y:i.transform[5],width:i.width,height:i.height}))};},number);pages.push(detail);await page.locator('#page').screenshot({path:metadata.pages===1?output:output.replace(/\.png$/,`-${number}.png`)});}
fs.writeFileSync(output.replace(/\.png$/,'.json'),JSON.stringify({source,pages},null,2));console.log(JSON.stringify({pages:metadata.pages,dimensions:pages.map(p=>p.dimensions),output}));
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(error=>{console.error(error);process.exitCode=1;});
